language: cpp

env:
  global:
    - PATH=${TRAVIS_BUILD_DIR}/gcc-arm-none-eabi/bin:${PATH}

compiler:
  - gcc

install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get install libc6:i386 libstdc++6:i386  
  - ./travis_install

script:
  - make clean build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  acl: public_read
  local-dir: firmwarebin/
  upload-dir: ${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  bucket: $HEX_BUCKET
  region: us-east-2
  skip_cleanup: true
  on:
    repo: Opentrons/SmoothiewareOT
    all_branches: true

notifications:
  email:
    on_failure: change
