language: cpp

compiler:
  - gcc

before_script:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq
 - sudo apt-get install -y --force-yes gcc-arm-none-eabi

# install:
#   - make install

script:
  - make clean build

# whitelist
branches:
  only:
    - edge

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local-dir: FirmwareBin/
  bucket: opentrons-smoothieware-hex
  region: us-east-2

notifications:
  email:
    on_failure: change
