language: cpp

compiler:
  - gcc

before_script:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq
 - sudo apt-get install -y --force-yes gcc-arm-none-eabi

script:
  - make clean build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local-dir: firmwarebin/
  upload-dir: $TRAVIS-BRANCH
  bucket: $HEX_BUCKET
  region: us-east-2
  on:
    repo: Opentrons/SmoothiewareOT
    all_branches: true

notifications:
  email:
    on_failure: change
